name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/test_requirements.txt
        pip install -e .
        
    - name: Code style checks
      run: |
        black --check telegram_archive_explorer tests
        flake8 telegram_archive_explorer tests
        pylint telegram_archive_explorer tests
        mypy telegram_archive_explorer tests
        
    - name: Run tests
      run: |
        pytest tests/ --cov=telegram_archive_explorer --cov-report=xml --cov-report=term -v

    - name: Performance tests
      run: |
        pytest tests/ --benchmark-only -v
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
